// Cypress test: Login then navigate through various pages and apply filters/search
// Author: Generated by AI based on user instructions (2025-12-31)

/*
  Scenario outline (condensed):
  1. Login to dev environment with provided credentials
  2. Short-form -> Entry Points: change "Recent" to "Most popular"  and "All Collections" to "Telco"
  3. Short-form -> Library: change "Recent" dropdown and "All Channels" dropdown (select first visible option for demo)
  4. Short-form -> Uploads: search for the word "Test"
  5. Short-form -> Channels: search for "Flytel"
  6. Short-form -> Users: search for "Horizon"
  7. Campaign -> Library: change "Show All" dropdown (pick second option) and "All Channels" -> "Flytel"
  8. UGC -> Polls: search for "QA"
  9. UGC -> Comments: change the 3 dropdowns (Show all -> Approved, All Channels -> Flytel, Last 7 Days -> Last 3 Months)
 10. UGC -> Reports: change Last 7 Days -> Last 3 Months

  NOTE: This script purposely keeps selectors generic and relies on text-based lookup to remain future-proof.
*/

/** Utility helpers */
const humanDelay = 1200; // ms between visual actions
const humanWait = (ms = humanDelay) => cy.wait(ms);

// Click any visible element (button/div/span/a/etc.) that contains given text
const clickByContains = (text, opts = {}) => {
  cy.contains(text, { matchCase: false, timeout: 20000 })
    .filter(':visible')
    .first()
    .scrollIntoView()
    .click({ force: true, ...opts });
};

// Type into first visible input/search field
const typeSearch = (placeholderText, value) => {
  cy.get('input, textarea')
    .filter(':visible')
    .filter((i, el) => {
      const ph = (el.placeholder || '').toLowerCase();
      return ph.includes(placeholderText.toLowerCase());
    })
    .first()
    .clear({ force: true })
    .type(`${value}{enter}`, { delay: 100, force: true });
};

// Select dropdown option: click trigger then choose option text
const selectDropdown = (triggerText, optionText) => {
  clickByContains(triggerText);
  humanWait(500);
  clickByContains(optionText);
  humanWait(800);
};

// Navigate side-bar: open Short-form child if collapsed
const openSidebarItem = (parentText, childText) => {
  cy.get('body').then($body => {
    // ensure parent expanded
    if (childText) {
      const childVisible = $body.find(`*:contains("${childText}")`).filter(':visible').length > 0;
      if (!childVisible) {
        clickByContains(parentText);
        humanWait();
      }
      clickByContains(childText);
    } else {
      clickByContains(parentText);
    }
  });
};

// Login once at beginning
before(() => {
  const baseUrl = 'https://dev.shorts.macintosh-ix88.thinkflagship.com';
  cy.viewport(1920, 1080);
  cy.visit(`${baseUrl}/signin`);
  humanWait();

  // email
  cy.get('input[type="email"], input[name="email"], input[placeholder*="email" i]')
    .first()
    .should('be.visible')
    .clear()
    .type('demo@horizonexp.com');
  humanWait(600);

  // password
  cy.get('input[type="password"], input[name="password"], input[placeholder*="password" i]')
    .first()
    .should('be.visible')
    .clear()
    .type('lzh54u7p');
  humanWait(600);

  // submit
  cy.get('button[type="submit"], button:contains("Login"), button:contains("Sign in")').first().click({ force: true });

  // wait for dashboard / any app path
  cy.url({ timeout: 20000 }).should('include', '/app').then(() => humanWait(2000));
});

describe('Dashboard navigation & filtering smoke test', () => {
  it('performs navigation & filtering steps', () => {
    // 1. Entry Points page filters
    openSidebarItem('Short-form', 'Entry Points');
    humanWait();
    selectDropdown('Recent', 'Most popular');
    selectDropdown('All Collections', 'Telco');

    // 2. Library filters
    openSidebarItem('Short-form', 'Library');
    humanWait();
    selectDropdown('Recent', 'Most Popular');
    selectDropdown('All Channels', 'Flytel');

    // 3. Uploads search
    openSidebarItem('Short-form', 'Uploads');
    humanWait();
    typeSearch('search', 'Test');
    humanWait();

    // 4. Channels search
    openSidebarItem('Short-form', 'Channels');
    humanWait();
    typeSearch('search', 'Flytel');
    humanWait();

    // 5. Users search
    openSidebarItem('Short-form', 'Users');
    humanWait();
    typeSearch('search', 'Horizon');
    humanWait();

    // 6. Campaign Library filters
    openSidebarItem('Campaign', 'Library');
    humanWait();
    selectDropdown('Show All', 'Video campaigns'); // or Show campaigns if label differs
    selectDropdown('All Channels', 'Flytel');

    // 7. UGC Polls search
    openSidebarItem('UGC', 'Polls');
    humanWait();
    typeSearch('search', 'QA');
    humanWait();

    // 8. UGC Comments dropdowns
    openSidebarItem('UGC', 'Comments');
    humanWait();
    selectDropdown('Show all', 'Approved');
    selectDropdown('All Channels', 'Flytel');
    selectDropdown('Last 7 Days', 'Last 3 Months');

    // 9. UGC Reports time filter
    openSidebarItem('UGC', 'Reports');
    humanWait();
    selectDropdown('Last 7 Days', 'Last 3 Months');
    humanWait();
  });
});

